### ISSUE TITLE
Add tor pluggable transport interface?

### ISSUE THREAD

**Issue by ioerror** [stealth/fraud-bridge#1]
It would be quite interesting if it was possible for Tor to use fraud-bridge as a pluggable transport - here is the spec we wrote:

  https://gitweb.torproject.org/torspec.git/blob/HEAD:/pt-spec.txt

Is this something that you find interesting or useful?

**Comment by stealth** [comment]
Hah, finally resolved by having a paragraph on how to setup tor with it.
