### ISSUE TITLE
Tunnel Problem 

### ISSUE THREAD

**Issue by raminmalekghasemi** [stealth/fraud-bridge#5]
Hi On ubuntu 18
make and config inside and ouside for peers ip Now whena this line 

./fraud-bridge -u -R VALID-IP-ADDRESS  -i  -k @@@@
Run tunnel on mode icmp v4
say to me check syslog

and syslog

fraud-bridge[1401]: Warning: Not possible to chroot!: No such file or directory

**Comment by stealth** [comment]
its just a warning which can be ignored. However, if you want to profit from chroot safety, you should pass valid empty directory name to `-r`.

**Comment by stealth** [comment]
closing
